package com.sms.sendsms.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.sms.sendsms.database.Business;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table business.
*/
public class BusinessDao extends AbstractDao<Business, Long> {

    public static final String TABLENAME = "business";

    /**
     * Properties of entity Business.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property StoreCode = new Property(1, String.class, "storeCode", false, "storecode");
        public final static Property BusinessName = new Property(2, String.class, "businessName", false, "businessname");
        public final static Property Logo = new Property(3, String.class, "logo", false, "logo");
        public final static Property BackgroundImage = new Property(4, String.class, "backgroundImage", false, "backgroundimage");
        public final static Property BackgroundColor = new Property(5, String.class, "backgroundColor", false, "backgroundcolor");
        public final static Property HeaderColor = new Property(6, String.class, "headerColor", false, "headercolor");
        public final static Property FooterColor = new Property(7, String.class, "footerColor", false, "footercolor");
        public final static Property IfLogo = new Property(8, boolean.class, "ifLogo", false, "iflogo");
        public final static Property IfMail = new Property(9, boolean.class, "ifMail", false, "ifmail");
        public final static Property IfFacebook = new Property(10, boolean.class, "ifFacebook", false, "iffacebook");
        public final static Property IfTwitter = new Property(11, boolean.class, "ifTwitter", false, "iftwitter");
        public final static Property IfLinkedin = new Property(12, boolean.class, "ifLinkedin", false, "iflinkedin");
        public final static Property IfGoogleplus = new Property(13, boolean.class, "ifGoogleplus", false, "ifgoogleplus");
        public final static Property IfYoutube = new Property(14, boolean.class, "ifYoutube", false, "ifyoutube");
        public final static Property IfPhone = new Property(15, boolean.class, "ifPhone", false, "ifphone");
        public final static Property IfGallery = new Property(16, boolean.class, "ifGallery", false, "ifgallery");
        public final static Property IfAbout = new Property(17, boolean.class, "ifAbout", false, "ifabout");
        public final static Property IfWebsite = new Property(18, boolean.class, "ifWebsite", false, "ifwebsite");
        public final static Property IfMap = new Property(19, boolean.class, "ifMap", false, "ifmap");
        public final static Property IfPinterest = new Property(20, boolean.class, "ifPinterest", false, "ifpinterest");
        public final static Property IfAndroid = new Property(21, boolean.class, "ifAndroid", false, "ifandroid");
        public final static Property MainText = new Property(22, String.class, "mainText", false, "maintext");
        public final static Property MailIconColor = new Property(23, String.class, "mailIconColor", false, "mail_icon_color");
        public final static Property MailLabelColor = new Property(24, String.class, "mailLabelColor", false, "mail_label_color");
        public final static Property MailLabel = new Property(25, String.class, "mailLabel", false, "mail_label");
        public final static Property FacebookIconColor = new Property(26, String.class, "facebookIconColor", false, "facebook_icon_color");
        public final static Property FacebookLabelColor = new Property(27, String.class, "facebookLabelColor", false, "facebook_label_color");
        public final static Property FacebookLabel = new Property(28, String.class, "facebookLabel", false, "facebook_label");
        public final static Property TwitterIconColor = new Property(29, String.class, "twitterIconColor", false, "twitter_icon_color");
        public final static Property TwitterLabelColor = new Property(30, String.class, "twitterLabelColor", false, "twitter_label_color");
        public final static Property TwitterLabel = new Property(31, String.class, "twitterLabel", false, "twitter_label");
        public final static Property LinkedinIconColor = new Property(32, String.class, "linkedinIconColor", false, "linkedin_icon_color");
        public final static Property LinkedinLabelColor = new Property(33, String.class, "linkedinLabelColor", false, "linkedin_label_color");
        public final static Property LinkedinLabel = new Property(34, String.class, "linkedinLabel", false, "linkedin_label");
        public final static Property GoogleplusIconColor = new Property(35, String.class, "googleplusIconColor", false, "googleplus_icon_color");
        public final static Property GoogleplusLabelColor = new Property(36, String.class, "googleplusLabelColor", false, "googleplus_label_color");
        public final static Property GoogleplusLabel = new Property(37, String.class, "googleplusLabel", false, "googleplus_label");
        public final static Property MailAddress = new Property(38, String.class, "mailAddress", false, "mail_address");
        public final static Property FacebookAddress = new Property(39, String.class, "facebookAddress", false, "facebook_address");
        public final static Property TwitterAddress = new Property(40, String.class, "twitterAddress", false, "twitter_address");
        public final static Property LinkedinAddress = new Property(41, String.class, "linkedinAddress", false, "linkedin_address");
        public final static Property GoogleplusAddress = new Property(42, String.class, "googleplusAddress", false, "googleplus_address");
        public final static Property YoutubeIconColor = new Property(43, String.class, "youtubeIconColor", false, "youtube_icon_color");
        public final static Property YoutubeLabelColor = new Property(44, String.class, "youtubeLabelColor", false, "youtube_label_color");
        public final static Property YoutubeLabel = new Property(45, String.class, "youtubeLabel", false, "youtube_label");
        public final static Property YoutubeAddress = new Property(46, String.class, "youtubeAddress", false, "youtube_address");
        public final static Property PhoneLabelColor = new Property(47, String.class, "phoneLabelColor", false, "phone_label_color");
        public final static Property PhoneIconColor = new Property(48, String.class, "phoneIconColor", false, "phone_icon_color");
        public final static Property PhoneLabel = new Property(49, String.class, "phoneLabel", false, "phone_label");
        public final static Property PhoneAddress = new Property(50, String.class, "phoneAddress", false, "phone_address");
        public final static Property GalleryIconColor = new Property(51, String.class, "galleryIconColor", false, "gallery_icon_color");
        public final static Property GalleryLabelColor = new Property(52, String.class, "galleryLabelColor", false, "gallery_label_color");
        public final static Property GalleryLabel = new Property(53, String.class, "galleryLabel", false, "gallery_label");
        public final static Property GalleryAddress = new Property(54, String.class, "galleryAddress", false, "gallery_address");
        public final static Property AboutIconColor = new Property(55, String.class, "aboutIconColor", false, "about_icon_color");
        public final static Property AboutLabelColor = new Property(56, String.class, "aboutLabelColor", false, "about_label_color");
        public final static Property AboutLabel = new Property(57, String.class, "aboutLabel", false, "about_label");
        public final static Property AboutAddress = new Property(58, String.class, "aboutAddress", false, "about_address");
        public final static Property WebsiteIconColor = new Property(59, String.class, "websiteIconColor", false, "website_icon_color");
        public final static Property WebsiteLabelColor = new Property(60, String.class, "websiteLabelColor", false, "website_label_color");
        public final static Property WebsiteLabel = new Property(61, String.class, "websiteLabel", false, "website_label");
        public final static Property WebsiteAddress = new Property(62, String.class, "websiteAddress", false, "website_address");
        public final static Property MapIconColor = new Property(63, String.class, "mapIconColor", false, "map_icon_color");
        public final static Property MapLabelColor = new Property(64, String.class, "mapLabelColor", false, "map_label_color");
        public final static Property MapLabel = new Property(65, String.class, "mapLabel", false, "map_label");
        public final static Property MapAddress = new Property(66, String.class, "mapAddress", false, "map_address");
        public final static Property PinterestIconColor = new Property(67, String.class, "pinterestIconColor", false, "pinterest_icon_color");
        public final static Property PinterestLabelColor = new Property(68, String.class, "pinterestLabelColor", false, "pinterest_label_color");
        public final static Property PinterestLabel = new Property(69, String.class, "pinterestLabel", false, "pinterest_label");
        public final static Property PinterestAddress = new Property(70, String.class, "pinterestAddress", false, "pinterest_address");
        public final static Property AndroidIconColor = new Property(71, String.class, "androidIconColor", false, "android_icon_color");
        public final static Property AndroidLabelColor = new Property(72, String.class, "androidLabelColor", false, "android_label_color");
        public final static Property AndroidLabel = new Property(73, String.class, "androidLabel", false, "android_label");
        public final static Property AndroidAddress = new Property(74, String.class, "androidAddress", false, "android_address");
        public final static Property IfBusinessname = new Property(75, boolean.class, "ifBusinessname", false, "ifbusinessname");
        public final static Property BusinessnameColor = new Property(76, String.class, "businessnameColor", false, "businessname_color");
        public final static Property MaintextColor = new Property(77, String.class, "maintextColor", false, "maintext_color");
        public final static Property IfFooter = new Property(78, boolean.class, "ifFooter", false, "iffooter");
        public final static Property IfHeader = new Property(79, boolean.class, "ifHeader", false, "ifheader");
        public final static Property IfUserplus = new Property(80, boolean.class, "ifUserplus", false, "ifuserplus");
        public final static Property UserplusIconColor = new Property(81, String.class, "userplusIconColor", false, "userplus_icon_color");
        public final static Property UserplusLabelColor = new Property(82, String.class, "userplusLabelColor", false, "userplus_label_color");
        public final static Property UserplusLabel = new Property(83, String.class, "userplusLabel", false, "userplus_label");
        public final static Property Bitly = new Property(84, String.class, "bitly", false, "bitly");
        public final static Property Maskyoo = new Property(85, String.class, "maskyoo", false, "maskyoo");
        public final static Property Active = new Property(86, boolean.class, "active", false, "active");
        public final static Property AboutTextColor = new Property(87, String.class, "aboutTextColor", false, "about_text_color");
        public final static Property FooterIconsColor = new Property(88, String.class, "footerIconsColor", false, "footer_icons_color");
        public final static Property FooterIconsBackground = new Property(89, String.class, "footerIconsBackground", false, "footer_icons_background");
        public final static Property RealPhone = new Property(90, String.class, "realPhone", false, "realphone");
        public final static Property MonthlySms = new Property(91, int.class, "monthlySms", false, "monthlysms");
        public final static Property ChatIconColor = new Property(92, String.class, "chatIconColor", false, "chat_icon_color");
        public final static Property ChatLabelColor = new Property(93, String.class, "chatLabelColor", false, "chat_label_color");
        public final static Property ChatLabel = new Property(94, String.class, "chatLabel", false, "chat_label");
        public final static Property IfChat = new Property(95, boolean.class, "ifChat", false, "ifchat");
        public final static Property Test = new Property(96, int.class, "test", false, "test");
    };


    public BusinessDao(DaoConfig config) {
        super(config);
    }
    
    public BusinessDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'business' (" + //
                "'id' INTEGER PRIMARY KEY ," + // 0: id
                "'storecode' TEXT," + // 1: storeCode
                "'businessname' TEXT," + // 2: businessName
                "'logo' TEXT," + // 3: logo
                "'backgroundimage' TEXT NOT NULL ," + // 4: backgroundImage
                "'backgroundcolor' TEXT," + // 5: backgroundColor
                "'headercolor' TEXT," + // 6: headerColor
                "'footercolor' TEXT," + // 7: footerColor
                "'iflogo' INTEGER NOT NULL ," + // 8: ifLogo
                "'ifmail' INTEGER NOT NULL ," + // 9: ifMail
                "'iffacebook' INTEGER NOT NULL ," + // 10: ifFacebook
                "'iftwitter' INTEGER NOT NULL ," + // 11: ifTwitter
                "'iflinkedin' INTEGER NOT NULL ," + // 12: ifLinkedin
                "'ifgoogleplus' INTEGER NOT NULL ," + // 13: ifGoogleplus
                "'ifyoutube' INTEGER NOT NULL ," + // 14: ifYoutube
                "'ifphone' INTEGER NOT NULL ," + // 15: ifPhone
                "'ifgallery' INTEGER NOT NULL ," + // 16: ifGallery
                "'ifabout' INTEGER NOT NULL ," + // 17: ifAbout
                "'ifwebsite' INTEGER NOT NULL ," + // 18: ifWebsite
                "'ifmap' INTEGER NOT NULL ," + // 19: ifMap
                "'ifpinterest' INTEGER NOT NULL ," + // 20: ifPinterest
                "'ifandroid' INTEGER NOT NULL ," + // 21: ifAndroid
                "'maintext' TEXT," + // 22: mainText
                "'mail_icon_color' TEXT," + // 23: mailIconColor
                "'mail_label_color' TEXT," + // 24: mailLabelColor
                "'mail_label' TEXT," + // 25: mailLabel
                "'facebook_icon_color' TEXT," + // 26: facebookIconColor
                "'facebook_label_color' TEXT," + // 27: facebookLabelColor
                "'facebook_label' TEXT," + // 28: facebookLabel
                "'twitter_icon_color' TEXT," + // 29: twitterIconColor
                "'twitter_label_color' TEXT," + // 30: twitterLabelColor
                "'twitter_label' TEXT," + // 31: twitterLabel
                "'linkedin_icon_color' TEXT," + // 32: linkedinIconColor
                "'linkedin_label_color' TEXT," + // 33: linkedinLabelColor
                "'linkedin_label' TEXT," + // 34: linkedinLabel
                "'googleplus_icon_color' TEXT," + // 35: googleplusIconColor
                "'googleplus_label_color' TEXT," + // 36: googleplusLabelColor
                "'googleplus_label' TEXT," + // 37: googleplusLabel
                "'mail_address' TEXT," + // 38: mailAddress
                "'facebook_address' TEXT," + // 39: facebookAddress
                "'twitter_address' TEXT," + // 40: twitterAddress
                "'linkedin_address' TEXT," + // 41: linkedinAddress
                "'googleplus_address' TEXT," + // 42: googleplusAddress
                "'youtube_icon_color' TEXT," + // 43: youtubeIconColor
                "'youtube_label_color' TEXT," + // 44: youtubeLabelColor
                "'youtube_label' TEXT," + // 45: youtubeLabel
                "'youtube_address' TEXT," + // 46: youtubeAddress
                "'phone_label_color' TEXT," + // 47: phoneLabelColor
                "'phone_icon_color' TEXT," + // 48: phoneIconColor
                "'phone_label' TEXT," + // 49: phoneLabel
                "'phone_address' TEXT," + // 50: phoneAddress
                "'gallery_icon_color' TEXT," + // 51: galleryIconColor
                "'gallery_label_color' TEXT," + // 52: galleryLabelColor
                "'gallery_label' TEXT," + // 53: galleryLabel
                "'gallery_address' TEXT," + // 54: galleryAddress
                "'about_icon_color' TEXT," + // 55: aboutIconColor
                "'about_label_color' TEXT," + // 56: aboutLabelColor
                "'about_label' TEXT," + // 57: aboutLabel
                "'about_address' TEXT," + // 58: aboutAddress
                "'website_icon_color' TEXT," + // 59: websiteIconColor
                "'website_label_color' TEXT," + // 60: websiteLabelColor
                "'website_label' TEXT," + // 61: websiteLabel
                "'website_address' TEXT," + // 62: websiteAddress
                "'map_icon_color' TEXT," + // 63: mapIconColor
                "'map_label_color' TEXT," + // 64: mapLabelColor
                "'map_label' TEXT," + // 65: mapLabel
                "'map_address' TEXT," + // 66: mapAddress
                "'pinterest_icon_color' TEXT," + // 67: pinterestIconColor
                "'pinterest_label_color' TEXT," + // 68: pinterestLabelColor
                "'pinterest_label' TEXT," + // 69: pinterestLabel
                "'pinterest_address' TEXT," + // 70: pinterestAddress
                "'android_icon_color' TEXT," + // 71: androidIconColor
                "'android_label_color' TEXT," + // 72: androidLabelColor
                "'android_label' TEXT," + // 73: androidLabel
                "'android_address' TEXT," + // 74: androidAddress
                "'ifbusinessname' INTEGER NOT NULL ," + // 75: ifBusinessname
                "'businessname_color' TEXT," + // 76: businessnameColor
                "'maintext_color' TEXT," + // 77: maintextColor
                "'iffooter' INTEGER NOT NULL ," + // 78: ifFooter
                "'ifheader' INTEGER NOT NULL ," + // 79: ifHeader
                "'ifuserplus' INTEGER NOT NULL ," + // 80: ifUserplus
                "'userplus_icon_color' TEXT," + // 81: userplusIconColor
                "'userplus_label_color' TEXT," + // 82: userplusLabelColor
                "'userplus_label' TEXT," + // 83: userplusLabel
                "'bitly' TEXT," + // 84: bitly
                "'maskyoo' TEXT," + // 85: maskyoo
                "'active' INTEGER NOT NULL ," + // 86: active
                "'about_text_color' TEXT," + // 87: aboutTextColor
                "'footer_icons_color' TEXT," + // 88: footerIconsColor
                "'footer_icons_background' TEXT," + // 89: footerIconsBackground
                "'realphone' TEXT," + // 90: realPhone
                "'monthlysms' INTEGER NOT NULL ," + // 91: monthlySms
                "'chat_icon_color' TEXT," + // 92: chatIconColor
                "'chat_label_color' TEXT," + // 93: chatLabelColor
                "'chat_label' TEXT," + // 94: chatLabel
                "'ifchat' INTEGER NOT NULL ," + // 95: ifChat
                "'test' INTEGER NOT NULL );"); // 96: test
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'business'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Business entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String storeCode = entity.getStoreCode();
        if (storeCode != null) {
            stmt.bindString(2, storeCode);
        }
 
        String businessName = entity.getBusinessName();
        if (businessName != null) {
            stmt.bindString(3, businessName);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(4, logo);
        }
        stmt.bindString(5, entity.getBackgroundImage());
 
        String backgroundColor = entity.getBackgroundColor();
        if (backgroundColor != null) {
            stmt.bindString(6, backgroundColor);
        }
 
        String headerColor = entity.getHeaderColor();
        if (headerColor != null) {
            stmt.bindString(7, headerColor);
        }
 
        String footerColor = entity.getFooterColor();
        if (footerColor != null) {
            stmt.bindString(8, footerColor);
        }
        stmt.bindLong(9, entity.getIfLogo() ? 1l: 0l);
        stmt.bindLong(10, entity.getIfMail() ? 1l: 0l);
        stmt.bindLong(11, entity.getIfFacebook() ? 1l: 0l);
        stmt.bindLong(12, entity.getIfTwitter() ? 1l: 0l);
        stmt.bindLong(13, entity.getIfLinkedin() ? 1l: 0l);
        stmt.bindLong(14, entity.getIfGoogleplus() ? 1l: 0l);
        stmt.bindLong(15, entity.getIfYoutube() ? 1l: 0l);
        stmt.bindLong(16, entity.getIfPhone() ? 1l: 0l);
        stmt.bindLong(17, entity.getIfGallery() ? 1l: 0l);
        stmt.bindLong(18, entity.getIfAbout() ? 1l: 0l);
        stmt.bindLong(19, entity.getIfWebsite() ? 1l: 0l);
        stmt.bindLong(20, entity.getIfMap() ? 1l: 0l);
        stmt.bindLong(21, entity.getIfPinterest() ? 1l: 0l);
        stmt.bindLong(22, entity.getIfAndroid() ? 1l: 0l);
 
        String mainText = entity.getMainText();
        if (mainText != null) {
            stmt.bindString(23, mainText);
        }
 
        String mailIconColor = entity.getMailIconColor();
        if (mailIconColor != null) {
            stmt.bindString(24, mailIconColor);
        }
 
        String mailLabelColor = entity.getMailLabelColor();
        if (mailLabelColor != null) {
            stmt.bindString(25, mailLabelColor);
        }
 
        String mailLabel = entity.getMailLabel();
        if (mailLabel != null) {
            stmt.bindString(26, mailLabel);
        }
 
        String facebookIconColor = entity.getFacebookIconColor();
        if (facebookIconColor != null) {
            stmt.bindString(27, facebookIconColor);
        }
 
        String facebookLabelColor = entity.getFacebookLabelColor();
        if (facebookLabelColor != null) {
            stmt.bindString(28, facebookLabelColor);
        }
 
        String facebookLabel = entity.getFacebookLabel();
        if (facebookLabel != null) {
            stmt.bindString(29, facebookLabel);
        }
 
        String twitterIconColor = entity.getTwitterIconColor();
        if (twitterIconColor != null) {
            stmt.bindString(30, twitterIconColor);
        }
 
        String twitterLabelColor = entity.getTwitterLabelColor();
        if (twitterLabelColor != null) {
            stmt.bindString(31, twitterLabelColor);
        }
 
        String twitterLabel = entity.getTwitterLabel();
        if (twitterLabel != null) {
            stmt.bindString(32, twitterLabel);
        }
 
        String linkedinIconColor = entity.getLinkedinIconColor();
        if (linkedinIconColor != null) {
            stmt.bindString(33, linkedinIconColor);
        }
 
        String linkedinLabelColor = entity.getLinkedinLabelColor();
        if (linkedinLabelColor != null) {
            stmt.bindString(34, linkedinLabelColor);
        }
 
        String linkedinLabel = entity.getLinkedinLabel();
        if (linkedinLabel != null) {
            stmt.bindString(35, linkedinLabel);
        }
 
        String googleplusIconColor = entity.getGoogleplusIconColor();
        if (googleplusIconColor != null) {
            stmt.bindString(36, googleplusIconColor);
        }
 
        String googleplusLabelColor = entity.getGoogleplusLabelColor();
        if (googleplusLabelColor != null) {
            stmt.bindString(37, googleplusLabelColor);
        }
 
        String googleplusLabel = entity.getGoogleplusLabel();
        if (googleplusLabel != null) {
            stmt.bindString(38, googleplusLabel);
        }
 
        String mailAddress = entity.getMailAddress();
        if (mailAddress != null) {
            stmt.bindString(39, mailAddress);
        }
 
        String facebookAddress = entity.getFacebookAddress();
        if (facebookAddress != null) {
            stmt.bindString(40, facebookAddress);
        }
 
        String twitterAddress = entity.getTwitterAddress();
        if (twitterAddress != null) {
            stmt.bindString(41, twitterAddress);
        }
 
        String linkedinAddress = entity.getLinkedinAddress();
        if (linkedinAddress != null) {
            stmt.bindString(42, linkedinAddress);
        }
 
        String googleplusAddress = entity.getGoogleplusAddress();
        if (googleplusAddress != null) {
            stmt.bindString(43, googleplusAddress);
        }
 
        String youtubeIconColor = entity.getYoutubeIconColor();
        if (youtubeIconColor != null) {
            stmt.bindString(44, youtubeIconColor);
        }
 
        String youtubeLabelColor = entity.getYoutubeLabelColor();
        if (youtubeLabelColor != null) {
            stmt.bindString(45, youtubeLabelColor);
        }
 
        String youtubeLabel = entity.getYoutubeLabel();
        if (youtubeLabel != null) {
            stmt.bindString(46, youtubeLabel);
        }
 
        String youtubeAddress = entity.getYoutubeAddress();
        if (youtubeAddress != null) {
            stmt.bindString(47, youtubeAddress);
        }
 
        String phoneLabelColor = entity.getPhoneLabelColor();
        if (phoneLabelColor != null) {
            stmt.bindString(48, phoneLabelColor);
        }
 
        String phoneIconColor = entity.getPhoneIconColor();
        if (phoneIconColor != null) {
            stmt.bindString(49, phoneIconColor);
        }
 
        String phoneLabel = entity.getPhoneLabel();
        if (phoneLabel != null) {
            stmt.bindString(50, phoneLabel);
        }
 
        String phoneAddress = entity.getPhoneAddress();
        if (phoneAddress != null) {
            stmt.bindString(51, phoneAddress);
        }
 
        String galleryIconColor = entity.getGalleryIconColor();
        if (galleryIconColor != null) {
            stmt.bindString(52, galleryIconColor);
        }
 
        String galleryLabelColor = entity.getGalleryLabelColor();
        if (galleryLabelColor != null) {
            stmt.bindString(53, galleryLabelColor);
        }
 
        String galleryLabel = entity.getGalleryLabel();
        if (galleryLabel != null) {
            stmt.bindString(54, galleryLabel);
        }
 
        String galleryAddress = entity.getGalleryAddress();
        if (galleryAddress != null) {
            stmt.bindString(55, galleryAddress);
        }
 
        String aboutIconColor = entity.getAboutIconColor();
        if (aboutIconColor != null) {
            stmt.bindString(56, aboutIconColor);
        }
 
        String aboutLabelColor = entity.getAboutLabelColor();
        if (aboutLabelColor != null) {
            stmt.bindString(57, aboutLabelColor);
        }
 
        String aboutLabel = entity.getAboutLabel();
        if (aboutLabel != null) {
            stmt.bindString(58, aboutLabel);
        }
 
        String aboutAddress = entity.getAboutAddress();
        if (aboutAddress != null) {
            stmt.bindString(59, aboutAddress);
        }
 
        String websiteIconColor = entity.getWebsiteIconColor();
        if (websiteIconColor != null) {
            stmt.bindString(60, websiteIconColor);
        }
 
        String websiteLabelColor = entity.getWebsiteLabelColor();
        if (websiteLabelColor != null) {
            stmt.bindString(61, websiteLabelColor);
        }
 
        String websiteLabel = entity.getWebsiteLabel();
        if (websiteLabel != null) {
            stmt.bindString(62, websiteLabel);
        }
 
        String websiteAddress = entity.getWebsiteAddress();
        if (websiteAddress != null) {
            stmt.bindString(63, websiteAddress);
        }
 
        String mapIconColor = entity.getMapIconColor();
        if (mapIconColor != null) {
            stmt.bindString(64, mapIconColor);
        }
 
        String mapLabelColor = entity.getMapLabelColor();
        if (mapLabelColor != null) {
            stmt.bindString(65, mapLabelColor);
        }
 
        String mapLabel = entity.getMapLabel();
        if (mapLabel != null) {
            stmt.bindString(66, mapLabel);
        }
 
        String mapAddress = entity.getMapAddress();
        if (mapAddress != null) {
            stmt.bindString(67, mapAddress);
        }
 
        String pinterestIconColor = entity.getPinterestIconColor();
        if (pinterestIconColor != null) {
            stmt.bindString(68, pinterestIconColor);
        }
 
        String pinterestLabelColor = entity.getPinterestLabelColor();
        if (pinterestLabelColor != null) {
            stmt.bindString(69, pinterestLabelColor);
        }
 
        String pinterestLabel = entity.getPinterestLabel();
        if (pinterestLabel != null) {
            stmt.bindString(70, pinterestLabel);
        }
 
        String pinterestAddress = entity.getPinterestAddress();
        if (pinterestAddress != null) {
            stmt.bindString(71, pinterestAddress);
        }
 
        String androidIconColor = entity.getAndroidIconColor();
        if (androidIconColor != null) {
            stmt.bindString(72, androidIconColor);
        }
 
        String androidLabelColor = entity.getAndroidLabelColor();
        if (androidLabelColor != null) {
            stmt.bindString(73, androidLabelColor);
        }
 
        String androidLabel = entity.getAndroidLabel();
        if (androidLabel != null) {
            stmt.bindString(74, androidLabel);
        }
 
        String androidAddress = entity.getAndroidAddress();
        if (androidAddress != null) {
            stmt.bindString(75, androidAddress);
        }
        stmt.bindLong(76, entity.getIfBusinessname() ? 1l: 0l);
 
        String businessnameColor = entity.getBusinessnameColor();
        if (businessnameColor != null) {
            stmt.bindString(77, businessnameColor);
        }
 
        String maintextColor = entity.getMaintextColor();
        if (maintextColor != null) {
            stmt.bindString(78, maintextColor);
        }
        stmt.bindLong(79, entity.getIfFooter() ? 1l: 0l);
        stmt.bindLong(80, entity.getIfHeader() ? 1l: 0l);
        stmt.bindLong(81, entity.getIfUserplus() ? 1l: 0l);
 
        String userplusIconColor = entity.getUserplusIconColor();
        if (userplusIconColor != null) {
            stmt.bindString(82, userplusIconColor);
        }
 
        String userplusLabelColor = entity.getUserplusLabelColor();
        if (userplusLabelColor != null) {
            stmt.bindString(83, userplusLabelColor);
        }
 
        String userplusLabel = entity.getUserplusLabel();
        if (userplusLabel != null) {
            stmt.bindString(84, userplusLabel);
        }
 
        String bitly = entity.getBitly();
        if (bitly != null) {
            stmt.bindString(85, bitly);
        }
 
        String maskyoo = entity.getMaskyoo();
        if (maskyoo != null) {
            stmt.bindString(86, maskyoo);
        }
        stmt.bindLong(87, entity.getActive() ? 1l: 0l);
 
        String aboutTextColor = entity.getAboutTextColor();
        if (aboutTextColor != null) {
            stmt.bindString(88, aboutTextColor);
        }
 
        String footerIconsColor = entity.getFooterIconsColor();
        if (footerIconsColor != null) {
            stmt.bindString(89, footerIconsColor);
        }
 
        String footerIconsBackground = entity.getFooterIconsBackground();
        if (footerIconsBackground != null) {
            stmt.bindString(90, footerIconsBackground);
        }
 
        String realPhone = entity.getRealPhone();
        if (realPhone != null) {
            stmt.bindString(91, realPhone);
        }
        stmt.bindLong(92, entity.getMonthlySms());
 
        String chatIconColor = entity.getChatIconColor();
        if (chatIconColor != null) {
            stmt.bindString(93, chatIconColor);
        }
 
        String chatLabelColor = entity.getChatLabelColor();
        if (chatLabelColor != null) {
            stmt.bindString(94, chatLabelColor);
        }
 
        String chatLabel = entity.getChatLabel();
        if (chatLabel != null) {
            stmt.bindString(95, chatLabel);
        }
        stmt.bindLong(96, entity.getIfChat() ? 1l: 0l);
        stmt.bindLong(97, entity.getTest());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Business readEntity(Cursor cursor, int offset) {
        Business entity = new Business( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // storeCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // businessName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // logo
            cursor.getString(offset + 4), // backgroundImage
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // backgroundColor
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // headerColor
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // footerColor
            cursor.getShort(offset + 8) != 0, // ifLogo
            cursor.getShort(offset + 9) != 0, // ifMail
            cursor.getShort(offset + 10) != 0, // ifFacebook
            cursor.getShort(offset + 11) != 0, // ifTwitter
            cursor.getShort(offset + 12) != 0, // ifLinkedin
            cursor.getShort(offset + 13) != 0, // ifGoogleplus
            cursor.getShort(offset + 14) != 0, // ifYoutube
            cursor.getShort(offset + 15) != 0, // ifPhone
            cursor.getShort(offset + 16) != 0, // ifGallery
            cursor.getShort(offset + 17) != 0, // ifAbout
            cursor.getShort(offset + 18) != 0, // ifWebsite
            cursor.getShort(offset + 19) != 0, // ifMap
            cursor.getShort(offset + 20) != 0, // ifPinterest
            cursor.getShort(offset + 21) != 0, // ifAndroid
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // mainText
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // mailIconColor
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // mailLabelColor
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // mailLabel
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // facebookIconColor
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // facebookLabelColor
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // facebookLabel
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // twitterIconColor
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // twitterLabelColor
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // twitterLabel
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // linkedinIconColor
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // linkedinLabelColor
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // linkedinLabel
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // googleplusIconColor
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // googleplusLabelColor
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // googleplusLabel
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // mailAddress
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // facebookAddress
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // twitterAddress
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // linkedinAddress
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // googleplusAddress
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // youtubeIconColor
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // youtubeLabelColor
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // youtubeLabel
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // youtubeAddress
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // phoneLabelColor
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // phoneIconColor
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // phoneLabel
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // phoneAddress
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // galleryIconColor
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // galleryLabelColor
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // galleryLabel
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // galleryAddress
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // aboutIconColor
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // aboutLabelColor
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // aboutLabel
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // aboutAddress
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // websiteIconColor
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // websiteLabelColor
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // websiteLabel
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // websiteAddress
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // mapIconColor
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // mapLabelColor
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // mapLabel
            cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66), // mapAddress
            cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67), // pinterestIconColor
            cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68), // pinterestLabelColor
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // pinterestLabel
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // pinterestAddress
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // androidIconColor
            cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72), // androidLabelColor
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // androidLabel
            cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74), // androidAddress
            cursor.getShort(offset + 75) != 0, // ifBusinessname
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // businessnameColor
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // maintextColor
            cursor.getShort(offset + 78) != 0, // ifFooter
            cursor.getShort(offset + 79) != 0, // ifHeader
            cursor.getShort(offset + 80) != 0, // ifUserplus
            cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81), // userplusIconColor
            cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82), // userplusLabelColor
            cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83), // userplusLabel
            cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84), // bitly
            cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85), // maskyoo
            cursor.getShort(offset + 86) != 0, // active
            cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87), // aboutTextColor
            cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88), // footerIconsColor
            cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89), // footerIconsBackground
            cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90), // realPhone
            cursor.getInt(offset + 91), // monthlySms
            cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92), // chatIconColor
            cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93), // chatLabelColor
            cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94), // chatLabel
            cursor.getShort(offset + 95) != 0, // ifChat
            cursor.getInt(offset + 96) // test
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Business entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStoreCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBusinessName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLogo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBackgroundImage(cursor.getString(offset + 4));
        entity.setBackgroundColor(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setHeaderColor(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFooterColor(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIfLogo(cursor.getShort(offset + 8) != 0);
        entity.setIfMail(cursor.getShort(offset + 9) != 0);
        entity.setIfFacebook(cursor.getShort(offset + 10) != 0);
        entity.setIfTwitter(cursor.getShort(offset + 11) != 0);
        entity.setIfLinkedin(cursor.getShort(offset + 12) != 0);
        entity.setIfGoogleplus(cursor.getShort(offset + 13) != 0);
        entity.setIfYoutube(cursor.getShort(offset + 14) != 0);
        entity.setIfPhone(cursor.getShort(offset + 15) != 0);
        entity.setIfGallery(cursor.getShort(offset + 16) != 0);
        entity.setIfAbout(cursor.getShort(offset + 17) != 0);
        entity.setIfWebsite(cursor.getShort(offset + 18) != 0);
        entity.setIfMap(cursor.getShort(offset + 19) != 0);
        entity.setIfPinterest(cursor.getShort(offset + 20) != 0);
        entity.setIfAndroid(cursor.getShort(offset + 21) != 0);
        entity.setMainText(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setMailIconColor(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setMailLabelColor(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setMailLabel(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setFacebookIconColor(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setFacebookLabelColor(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setFacebookLabel(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTwitterIconColor(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setTwitterLabelColor(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTwitterLabel(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setLinkedinIconColor(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setLinkedinLabelColor(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setLinkedinLabel(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setGoogleplusIconColor(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setGoogleplusLabelColor(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setGoogleplusLabel(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setMailAddress(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setFacebookAddress(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setTwitterAddress(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setLinkedinAddress(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setGoogleplusAddress(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setYoutubeIconColor(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setYoutubeLabelColor(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setYoutubeLabel(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setYoutubeAddress(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setPhoneLabelColor(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setPhoneIconColor(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setPhoneLabel(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setPhoneAddress(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setGalleryIconColor(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setGalleryLabelColor(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setGalleryLabel(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setGalleryAddress(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setAboutIconColor(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setAboutLabelColor(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setAboutLabel(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setAboutAddress(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setWebsiteIconColor(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setWebsiteLabelColor(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setWebsiteLabel(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setWebsiteAddress(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setMapIconColor(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setMapLabelColor(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setMapLabel(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setMapAddress(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
        entity.setPinterestIconColor(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setPinterestLabelColor(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setPinterestLabel(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setPinterestAddress(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setAndroidIconColor(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setAndroidLabelColor(cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72));
        entity.setAndroidLabel(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setAndroidAddress(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setIfBusinessname(cursor.getShort(offset + 75) != 0);
        entity.setBusinessnameColor(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setMaintextColor(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setIfFooter(cursor.getShort(offset + 78) != 0);
        entity.setIfHeader(cursor.getShort(offset + 79) != 0);
        entity.setIfUserplus(cursor.getShort(offset + 80) != 0);
        entity.setUserplusIconColor(cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81));
        entity.setUserplusLabelColor(cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82));
        entity.setUserplusLabel(cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83));
        entity.setBitly(cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84));
        entity.setMaskyoo(cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85));
        entity.setActive(cursor.getShort(offset + 86) != 0);
        entity.setAboutTextColor(cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87));
        entity.setFooterIconsColor(cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88));
        entity.setFooterIconsBackground(cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89));
        entity.setRealPhone(cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90));
        entity.setMonthlySms(cursor.getInt(offset + 91));
        entity.setChatIconColor(cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92));
        entity.setChatLabelColor(cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93));
        entity.setChatLabel(cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94));
        entity.setIfChat(cursor.getShort(offset + 95) != 0);
        entity.setTest(cursor.getInt(offset + 96));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Business entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Business entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
